# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Restructured"
license = "MIT"
licenselink = "https://github.com/fisodd/hugo-restructured/blob/master/LICENSE"
description = "A responsive blog theme utilizing reStructuredText markup"
homepage = "http://github.com/fisodd/hugo-restructured"
tags = ["restructuredtext", "responsive"]
features = ["sidebars", "figures"]
min_version = 0.20

[author]
  name = "Alexander Carlton"
  homepage = "http://fisodd.com/"

